### ISSUE TITLE
Thread count has no effect on gpt4all-j

### ISSUE THREAD

**Issue by fHachenberg** [go-skynet/LocalAI#148] opened 2023-05-02 04:47 UTC
Hi there, thanks for creating this amazing project! I noticed that if I use gpt4all-j in local-ai, I always end up with 4 threads. With gpt2 for instance, it works however. I think the issue is either in this wrapper or the gpt4all-j-cpp-code itself.

**Comment by mudler** [comment] 2023-05-02 07:11
Good catch! seems indeed a regression while using the new binding code

**Comment by thebennos** [comment] 2023-05-12 16:35
confirming. tried to start with 8 threads on startup and it starts only with 4 threads.

**Comment by mudler** [comment] 2023-05-13 07:37
Thanks for the feedback - Looks like a regression, fix is in #249

**Closed** 2023-05-13 07:37 UTC
Labels: bug
