### ISSUE TITLE
Error building LocalAI tag v1.25.0 on Apple Silicon

### ISSUE THREAD

**Issue by elepedus** [go-skynet/LocalAI#970] opened 2023-08-28 08:18 UTC
**LocalAI version:**
v.1.25.0

**Environment, CPU architecture, OS, and Version:**
Darwin A2780.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64

**Describe the bug**
`make build` fails. Last few lines of output are:
```
pkg/backend/llm/llama/llama.go:31:9: undefined: llama.WithRopeFreqBase
pkg/backend/llm/llama/llama.go:32:9: undefined: llama.WithRopeFreqScale
pkg/backend/llm/llama/llama.go:36:39: undefined: llama.SetMulMatQ
pkg/backend/llm/llama/llama.go:40:39: undefined: llama.SetLoraAdapter
pkg/backend/llm/llama/llama.go:44:39: undefined: llama.SetLoraBase
pkg/backend/llm/llama/llama.go:94:24: cannot use opts.Temperature (variable of type float32) as float64 value in argument to llama.SetTemperature
pkg/backend/llm/llama/llama.go:95:17: cannot use opts.TopP (variable of type float32) as float64 value in argument to llama.SetTopP
pkg/backend/llm/llama/llama.go:99:9: undefined: llama.WithGrammar
pkg/backend/llm/llama/llama.go:100:9: undefined: llama.SetRopeFreqBase
pkg/backend/llm/llama/llama.go:101:9: undefined: llama.SetRopeFreqScale
pkg/backend/llm/llama/llama.go:101:9: too many errors
make: *** [backend-assets/grpc/llama] Error 1
```

**To Reproduce**
Check out tag v1.25.0, 

**Expected behavior**
The project should build without error

**Logs**
N/A

**Additional context**
N/A

**Comment by dave-gray101** [comment] 2023-08-28 18:36
@elepedus I can't reproduce this on my M1 mac. I'm able to `make build` both v1.25.0 and master (as of time of writing fe1b54).

Please run `make clean` then `make build` and if the error persists, can you share your hardware specs and any other details?

**Comment by InTheZ** [comment] 2023-09-10 15:38
I was able to build v1.25.0 on my M2 Macbook Air today as well on 13.5.2 and it seems to work as well as 1.24.1 (just upgraded). One note is that the current master builds but seems to produce gibberish output right now so make sure to use v1.25.0.

**Comment by Aisuko** [comment] 2023-09-14 01:34
Thanks for your feedback. We are closing this issue now. Please re-open this issue if you hit the error again. Thanks.

**Closed by Aisuko** 2023-09-14 01:34 UTC
Labels: bug, need-more-information
